// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzcy1igQII8b1Jn_e4eygb9hP41jO1-rk',
    appId: '1:706985453197:web:0a1939c2f7846333dca4c4',
    messagingSenderId: '706985453197',
    projectId: 'fleetpilote',
    authDomain: 'fleetpilote.firebaseapp.com',
    storageBucket: 'fleetpilote.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLtbZz3eDMByyhFCAXtDV4C5kQ-yz-lIw',
    appId: '1:706985453197:android:8ac83a499697a5c9dca4c4',
    messagingSenderId: '706985453197',
    projectId: 'fleetpilote',
    storageBucket: 'fleetpilote.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx67KohCXFU32HATAJIKivlmw-FsB0zcw',
    appId: '1:706985453197:ios:2ccba0b895fc921ddca4c4',
    messagingSenderId: '706985453197',
    projectId: 'fleetpilote',
    storageBucket: 'fleetpilote.firebasestorage.app',
    iosBundleId: 'com.example.fleetpilotApp',
  );
}
